import{a as f,S as m,i as n}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const p of t.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&s(p)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function y(o,r){const e=`https://pixabay.com/api/?key=43257853-194068c59ee252fa44b7d008e&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const t=await f.get(e);return!t.data.hits||t.data.hits.length===0?[]:t.data}catch(t){return console.error("Error fetching more images:",t),[]}}function b(){const o=document.querySelector(".gallery");o.innerHTML=""}function g(o){const r=document.querySelector(".gallery"),a=o.map(s=>`<li class="card">
    <a href="${s.largeImageURL}" data-lightbox="gallery-item">
      <img class="contentCard" src="${s.webformatURL}" alt="${s.tags}">
    </a>
    <div class="imgCard">
      <p><b>Likes:</b> ${s.likes}</p>
      <p><b>Views:</b> ${s.views}</p>
      <p><b>Comments:</b> ${s.comments}</p>
      <p><b>Downloads:</b> ${s.downloads}</p>
    </div></li>
  `).join("");r.insertAdjacentHTML("beforeend",a)}const u=new m(".gallery a",{captionsData:"alt",captionDelay:250}),w=document.getElementById("search-form"),E=document.getElementById("search-input"),c=document.querySelector(".loader"),i=document.getElementById("load");let l="";const h=15;let d=1;w.addEventListener("submit",async o=>{if(o.preventDefault(),l=E.value.trim(),d=1,i.style.display="none",!l){n.error({position:"topRight",title:"Error",message:"Please enter a keyword for search."});return}c.style.display="block",b();try{const r=await y(l,d);r.length===0?n.info({position:"topRight",title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(g(r.hits),u.refresh(),i.style.display="block"),r.totalHits<h&&(n.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."}),i.style.display="none")}catch(r){console.error("Error fetching images:",r),n.error({position:"topRight",title:"Error",message:"An error occurred while fetching images. Please try again later."})}finally{c.style.display="none"}});i.addEventListener("click",async()=>{d+=1,c.style.display="block";try{const o=await y(l,d);if(o.hits.length<h&&(i.style.display="none",n.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."})),g(o.hits),u.refresh(),o.hits.length>0){const r=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch(o){console.error("Error fetching more images:",o),n.error({position:"topRight",title:"Error",message:"An error occurred while fetching more images. Please try again later."})}finally{c.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
