import{a as u,S as b,i as a}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function c(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=c(t);fetch(t.href,o)}})();const g="43257853-194068c59ee252fa44b7d008e";let n=1,y="";const m=15;async function w(e){y=e,n=1;try{const r=await u.get("https://pixabay.com/api/",{params:{key:g,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:m}});if(r.status!==200)throw new Error("Network response was not ok");return r.data.hits}catch(r){return console.error("Error fetching images:",r),[]}}async function E(){n++;try{const e=await u.get("https://pixabay.com/api/",{params:{key:g,q:y,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:m}});if(e.status!==200)throw new Error("Network response was not ok");return e.data.hits}catch(e){return console.error("Error fetching more images:",e),[]}}function L(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(e){const r=document.querySelector(".gallery"),c=e.map(s=>`<li class="card">
    <a href="${s.largeImageURL}" data-lightbox="gallery-item">
      <img class="contentCard" src="${s.webformatURL}" alt="${s.tags}">
    </a>
    <div class="imgCard">
      <p><b>Likes:</b> ${s.likes}</p>
      <p><b>Views:</b> ${s.views}</p>
      <p><b>Comments:</b> ${s.comments}</p>
      <p><b>Downloads:</b> ${s.downloads}</p>
    </div></li>
  `).join("");r.insertAdjacentHTML("beforeend",c)}const f=new b(".gallery a",{captionsData:"alt",captionDelay:250}),I=document.getElementById("search-form"),v=document.getElementById("search-input"),i=document.querySelector(".loader"),d=document.getElementById("load");let p="";I.addEventListener("submit",async e=>{if(e.preventDefault(),p=v.value.trim(),!p){a.error({position:"topRight",title:"Error",message:"Please enter a keyword for search."});return}i.style.display="block",L();try{const r=await w(p);r.length===0?a.info({position:"topRight",title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(h(r),f.refresh(),d.style.display="block")}catch(r){console.error("Error fetching images:",r),a.error({position:"topRight",title:"Error",message:"An error occurred while fetching images. Please try again later."})}finally{i.style.display="none"}});d.addEventListener("click",async()=>{i.style.display="block";try{const e=await E();if(e.length>0){h(e),f.refresh();const r=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}else a.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."}),d.style.display="none"}catch(e){console.error("Error fetching more images:",e),a.error({position:"topRight",title:"Error",message:"An error occurred while fetching more images. Please try again later."})}finally{i.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
