import{a as h,S as m,i as a}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const d of t.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function y(o,r){const e=`https://pixabay.com/api/?key=43257853-194068c59ee252fa44b7d008e&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const t=await h.get(e);return!t.data.hits||t.data.hits.length===0?[]:t.data}catch(t){return console.error("Error fetching more images:",t),[]}}function b(){const o=document.querySelector(".gallery");o.innerHTML=""}function g(o){const r=document.querySelector(".gallery"),i=o.map(s=>`<li class="card">
    <a href="${s.largeImageURL}" data-lightbox="gallery-item">
      <img class="contentCard" src="${s.webformatURL}" alt="${s.tags}">
    </a>
    <div class="imgCard">
      <p><b>Likes:</b> ${s.likes}</p>
      <p><b>Views:</b> ${s.views}</p>
      <p><b>Comments:</b> ${s.comments}</p>
      <p><b>Downloads:</b> ${s.downloads}</p>
    </div></li>
  `).join("");r.insertAdjacentHTML("beforeend",i)}const u=new m(".gallery a",{captionsData:"alt",captionDelay:250}),w=document.getElementById("search-form"),E=document.getElementById("search-input"),l=document.querySelector(".loader"),c=document.getElementById("load");let n="";const f=15;let p=1;w.addEventListener("submit",async o=>{if(o.preventDefault(),n=E.value.trim(),!n){a.error({position:"topRight",title:"Error",message:"Please enter a keyword for search."});return}l.style.display="block",b();try{const r=await y(n);r.length===0?a.info({position:"topRight",title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(g(r.hits),u.refresh(),c.style.display="block"),r.totalHits<f&&(a.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none")}catch(r){console.error("Error fetching images:",r),a.error({position:"topRight",title:"Error",message:"An error occurred while fetching images. Please try again later."})}finally{l.style.display="none"}});c.addEventListener("click",async()=>{p+=1,l.style.display="block";try{const o=await y(n,p);if(o.totalHits%f&&(c.style.display="none",a.info({position:"topRight",title:"Info",message:"We're sorry, but you've reached the end of search results."})),g(o.hits),u.refresh(),o.length>0){const r=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch(o){console.error("Error fetching more images:",o),a.error({position:"topRight",title:"Error",message:"An error occurred while fetching more images. Please try again later."})}finally{l.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
